# Generated by Django 4.2.8 on 2024-01-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
