# Generated by Django 4.2.8 on 2024-01-06 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("post", "0002_comments_reactions_tags_votes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vouches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                ("vouches", models.JSONField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouches",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
