# Generated by Django 4.2.9 on 2024-01-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_vouches"),
    ]

    operations = [
        migrations.RenameField(model_name="tags", old_name="votes", new_name="tags",),
    ]
