"""
Django settings for watermelon project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# imports from python
from datetime import timedelta

from pathlib import Path

"""
    NOTICE: 1 - 

    TO DO : 1 - Secure MySQL Password
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-m)4c4jlms%hqju=(#vvj)3!vavdms4e8wt3pm^0y$ybckmh^1$"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

CREATE USER 'your_database_user'@'localhost' IDENTIFIED BY 'your_database_password';
GRANT ALL PRIVILEGES ON your_database_name.* TO 'your_database_user'@'localhost';
FLUSH PRIVILEGES;


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "generic_relations",
    "djoser",
    "debug_toolbar",
    "core", 
    "project",
    "post",
    "collection",
    "playground"
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "watermelon.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "watermelon.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        'NAME': 'watermelon',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': 'MysqlI3&29!'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


"""
    Initially created for Django Debug Toolbar
"""
INTERNAL_IPS = [
    "127.0.0.1",
    ]


"""
    model = core.User
    NOTICE :
        1 - This is used as default User class in all Apps except core

    RELATED FIELDS :
        - invitations_to_project_out : model = RequestToProject 
            : set of invitations to join projects that the user sent out;
        - requests_to_project_in : model = RequestToProject 
            : set of invitations and/or requests asking the user to join projects
        - projects : model = UserProjectItem 
            : set of links between this user and projects
        - removals_from_project_out : model = RemovalFromProject
            : set of removal requests to remove a user from project that this user sent out
        - 
"""
AUTH_USER_MODEL = 'core.User'


"""
    REST_FRAMEWORK SETTINGS

    SETTINGS ITEMS:
        - DEFAULT_AUTHENTICATION_CLASSES : I need to figure this out LATER, but I don't really need to know this now
"""
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES' : (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


"""
    SIMPLE_JWT SETTINGS

    SETTINGS ITEMS:
        - AUTH_HEADER_TYPES : I need to figure this out LATER, but I don't really need to know this now
        - ACCESS_TOKEN_LIFETIME : how long a user can stay logged in before automatic log out
"""
SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT',),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=5)
}
