"""
    AcceptRate
"""
ACCEPT_NEW_ASSOCIATE_VOTE_RATE = 0.6
REMOVE_ASSOCIATE_VOTE_RATE = 0.51


"""
    Deadline
"""
DEFAULT_DAYS_TO_PROJECT_DEADLINE = 14
DEFAULT_DAYS_TO_ACCESS_REQUEST_DEADLINE = 5
DEFAULT_DAYS_TO_REMOVAL_REQUEST_DEADLINE = 5


"""
    Progress
"""
DEFAULT_DATA_POINT_NUMBER_IN_PROGRESS = 20
DEFAULT_MINUTES_BETWEEN_DATA_POINT_IN_PROGRESS = 30
DEFAULT_POINT_DIFFERENCE_BETWEEN_DATA_POINT_IN_PROGRESS = 2


"""
    Session
"""
DEFAULT_INSTANT_SESSION_MINUTES_LIMIT = 10


"""
    Topic
"""
DEFAULT_TOPIC_TITLE_MAX_LENGTH = 100


"""
    Task
"""
# DEFAULT_TASK_DURATION_ESTIMATE = SESSION_DURATION/N, N = NUMBER OF TASKS IN THE SESSION
# AS THE USER MODIFIES THE DURATION, OTHER TASKS HAVE THEIR DEFAULT DURATION ESTIMATE ADJUSTED
# EXAMPLE: ONE 10 MINUTE SESSION HAS 4 TASKS OF DEFAULT 2:30 MN DURATION ESTIMATE EACH. ONCE I CHANGE DURATION OF ONE TASK
# TO 4 MN, ALL OTHER THREE SHOULD NOW HAVE 2 MN. IF I CHANGE ANOTHER ONE TO 3 MN, THEN WE HAVE 4, 3, 1:30, 1:30 


"""
    Difficulty
    TO DO : 1- Reevaluate the entire metrics and labels
"""
X_BASIC = 1
BASIC = 2
EASY = 4
MEDIUM = 6
POSSIBLE = 9
CHALLENGE = 15
HARD = 24
X_HARD = 38
EXTREME = 62
UNREAL = 100

DEFAULT_DIFFICULTY = EASY

DIFFICULTY_CHOICES = [
    (X_BASIC, "Extra Basic"),
    (BASIC, "Basic"),
    (EASY, "Easy"),
    (MEDIUM, "Medium"),
    (POSSIBLE, "Possible"),
    (CHALLENGE, "Challenge"),
    (HARD, "Hard"),
    (X_HARD, "Extra Hard"),
    (EXTREME, "Extreme"),
    (UNREAL, "Unreal")
]


"""
    Weight
    TO DO : 1- Reevaluate the entire metrics and labels
"""
IRRELEVANT_AT_THE_MOMENT = 1
POTENTIALLY_USEFUL = 2
GOOD_TO_HAVE = 4
BASIC_DEPENDENCE = 6
SMALL_DEPENDENCE = 9
AVERAGE_DEPENDENCE = 15
HIGH_DEPENDENCE = 24
HIGHER_DEPENDENCE = 38
ABSOLUTE_DEPENDENCE = 62
ALL_OF_IT = 100

DEFAULT_WEIGHT = BASIC_DEPENDENCE

WEIGHT_CHOICES = [
    (IRRELEVANT_AT_THE_MOMENT, "Irrelevant at the moment"),
    (POTENTIALLY_USEFUL, "Potentially Useful in the future"),
    (GOOD_TO_HAVE, "Good to have just in case"),
    (BASIC_DEPENDENCE, "Basic dependence"),
    (SMALL_DEPENDENCE, "Small Dependence"),
    (AVERAGE_DEPENDENCE, "Average dependence"),
    (HIGH_DEPENDENCE, "High dependence"),
    (HIGHER_DEPENDENCE, "Higher dependence"),
    (ABSOLUTE_DEPENDENCE, "Absolute dependence"),
    (ALL_OF_IT, "This is the entire project/subproject"),
]



