# Generated by Django 4.2.8 on 2024-01-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="user_access",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="project.useraccess",
            ),
        ),
        migrations.DeleteModel(name="Post",),
    ]
