# Generated by Django 4.2.8 on 2024-01-02 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_session_user_access_delete_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="user_access",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="project.useraccess",
            ),
        ),
    ]
