# Generated by Django 4.2.8 on 2024-01-06 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0003_alter_session_user_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccess",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_accesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
