# Generated by Django 4.2.8 on 2024-01-07 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0004_alter_useraccess_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="author_access",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="topics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
