# Generated by Django 4.2.8 on 2024-01-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_rename_author_access_topic_author"),
    ]

    operations = [
        migrations.RemoveField(model_name="topic", name="parent",),
        migrations.CreateModel(
            name="Topics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("topic_hierarchy", models.JSONField()),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="project.project",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
