# Generated by Django 4.2.8 on 2024-01-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_remove_topic_parent_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
