# Generated by Django 4.2.9 on 2024-01-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_alter_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
