# Generated by Django 4.2.9 on 2024-01-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0011_alter_session_start_at"),
    ]

    operations = [
        migrations.RenameModel(old_name="Topics", new_name="TopicHierarchy",),
    ]
