# Generated by Django 4.2.9 on 2024-01-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0013_topicinproject_delete_topichierarchy"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="is_declined",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
