# Generated by Django 4.2.9 on 2024-02-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0014_accessrequest_is_declined_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccess", old_name="is_valid", new_name="has_access",
        ),
        migrations.RemoveField(model_name="accessrequest", name="is_approved",),
        migrations.AddField(
            model_name="accessrequest",
            name="trashed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="progress",
            name="trashed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="trashed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="removalrequest",
            name="trashed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="trashed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="task", name="trashed_at", field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="trashed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="topicinproject",
            name="trashed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="useraccess",
            name="show_project",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="useraccess",
            name="trashed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
